### ISSUE TITLE
Install process hangs

### ISSUE THREAD

**Issue by Zorakie** [QuanTrieuPCYT/Dell-Latitude-5480_Hackintosh#4]
Hi,
I am struggling to install hackintosh on my Latitude E5480. All my attempts so far were termintated arount WhateverGreen and some graphic adapter error. That is Why I have searched model-specific EFI.

Unfortunately, it seems to have the same issue, although cannot really tell as this EFI has only graphical interface (= progress bar) so no output I could pass.

It hangs around 1/4 of progress and just halts there, doing nothing (even usb stick not flashing) ...
Tried to reset NVRAM.

Any guess, what could be wrong please?

**Comment by QuanTrieuPCYT** [comment]
Try turning on verbose boot (add -v into your boot-arg in your config.plist) and show me the logs where the process hangs

**Comment by Zorakie** [comment]
Hello, sorry for the delay.

I switched to verbose mode and it came down to the graphics adapter.

Now, I was just searching, trying and searching more, and I was able to actually make the laptop install and RUN.

However, the same (or similar) issue with the graphics adapter is preventing me to run the system correctly.

it is down to the config.plist file.

With Your PLIST file, the system just refuses to boot.
Right now, it just throws
OC: grabbed zero system-id for SB, this is not allowed.
I searched (there is not much about that) and I have disabled my secure boot. Also, there was a hint to check for the lilu kext to be first in the list, which indeed is.

I am attaching the config file I was able to at least boot with, but that config just showed my HD620 as 7MBs. In fact, it is much smaller in size, so that probably made other features broken (that I haven't found out about yet).
I searched more, there are some files for clover for various graphics, but they seem to be not compatible (they use Devices key in the config, you are using DeviceProperties, etc.). Long story short, trying to merge it resulted in more errors.
I am uploading the config file I was able at least to boot with.

Do you have any idea how to make this work?
(Well, it is the same laptop, it should be working, maybe it is again to some other BIOS settings?)

[config.txt](https://github.com/QuanTrieuPCYT/Dell-Latitude-5480_Hackintosh/files/8358157/config.txt)

(github does not allow plist to be uploaded, so I just changed the extension in case you need to open it in xcode or other plist editor, so no copy-paste, internal MIME should stay the same :) )

Thank you very much!

**Comment by Zorakie** [comment]
ok, do have an update:
the system-id was not related to the graphics. Needed to change SecureBootMode in config to Disabled instead of x86legacy.

However, the graphics issue persists.

The config provided just won't boot at all, throwing IsTypeCOnlySystem.

In order to boot at all, I needed to change graphics values by this guide ( https://dortania.github.io/OpenCore-Install-Guide/config-laptop.plist/kaby-lake.html#deviceproperties )
(for HD620 AAPL 00001B59 and device ID 16590000 - this results in bootable system, but the graphics adapter reports as only 7MBs)
Any ideas please?

**Comment by codigoperfeito** [comment]
tries with my EFI, makes the settings he sends on his GITHUB and then reinstalls with his EFI. 

`https://github.com/codigoperfeito/Hakintosh-Wesley-Dell5480`

**Comment by codigoperfeito** [comment]
remember, my efi is to Monterey, bluetooth and WIFI not is working to BigSur

**Comment by Zorakie** [comment]
@codigoperfeito Sorry, does not work at all :( 
On booting, it plays the mac sound, but the EFI crashes, instead volume selection or tool selection, it simply shows black screen and does nothing. 

I though that it could be due to broken BOOTx64.efi file or OpenCore.efi file, but it seems to be something in your config, because I have also tried merging this EFI build with just your config file and it hangs the same way as when I used fully your EFI. 

Then, the log file is generated in EFI volume stating:
00:000 00:000 OCM: Failed to start image - Already started
00:0008 00:0008 BS: Failed to start OpenCoreimage - already started

Any ideas?

I know that this is already more to be solved within the provided git repo, so for a chance @QuanTrieuPCYT any idea, what can be wrong with your build? (... or my computer)

Thank you all!

**Comment by Zorakie** [comment]
[config_with_grahics.txt](https://github.com/QuanTrieuPCYT/Dell-Latitude-5480_Hackintosh/files/8421496/config_with_grahics.txt)

ok, solved in the end... just replaced the graphics part from the @codigoperfeito build to the @QuanTrieuPCYT build and I have fully working graphics card. THANK YOU!

**Comment by QuanTrieuPCYT** [comment]
it's recommended to change the DVMT and graphics memory to get proper mac-like graphics. The old configurations worked for me because i changed those values in the BIOS.

Anyways congrats on getting it working 👍

**Comment by codigoperfeito** [comment]
@Zorakie congrats, i'm happy for you.
