### ISSUE TITLE
The CPU fan is 3000RPM all the time

### ISSUE THREAD

**Issue by RCKXv5** [QuanTrieuPCYT/Dell-Latitude-5480_Hackintosh#5]
From the beginning, I have a problem with the CPU fan speed. Although the processor is cold (around 40 degrees).

Any suggestions what to do, is this normal ?
![Zrzut ekranu 2022-03-31 o 12 32 47](https://user-images.githubusercontent.com/102731613/161035698-5f4823f8-c82f-4ee3-a15a-bb790e7b3d86.png)

**Comment by QuanTrieuPCYT** [comment]
haven't experienced this on my hack, but try removing CPUFriend kexts and feedback me

**Comment by RCKXv5** [comment]
Not run, show this:
`00:000 00:000 OC: Plist Kexts\CPUFriend.kext\Contents\Info.plist is missing for injected kext CPUFriend.kext (V1.2.4 | CPUFriend.kext)`

**Comment by codigoperfeito** [comment]
You can remove of config.split

**Comment by QuanTrieuPCYT** [comment]
> System not starting now OC showing this:
> `00:000 00:000 OC: Plist Kexts\CPUFriend.kext\Contents\Info.plist is missing for injected kext CPUFriend.kext (V1.2.4 | CPUFriend.kext)`

make sure to snapshot your efi after removing the kexts

**Comment by RCKXv5** [comment]
It's better now, thank you
