### ISSUE TITLE
Stuck in boot loop

### ISSUE THREAD

**Issue by EggyBoi** [QuanTrieuPCYT/Dell-Latitude-5480_Hackintosh#8]
I used the latest EFI file, validated it with OCAuxillaryTools, & tried booting OpenCore. The first time I did that, I was able to open the grub efi & adjusted the DVMT, but everytime after that has shown the Apple logo, played the startup chime, and then gone black and restarted the PC to loop infinitely. Any ideas?

**Comment by QuanTrieuPCYT** [comment]
Can you show me the verbose log?

**Comment by EggyBoi** [comment]
Sorry I’m kind of new to Hackintoshes, where would I get that?

**Comment by codigoperfeito** [comment]
you need change config of efi to when you join in system him make a log in your folder EFI, nome is "log.txt", you extract and past here.

**Comment by EggyBoi** [comment]
Okay, I reinstalled your EFI actually and now it's booting up Open Core, I can select the installer, & then the Apple logo shows up with a loading bar. It gets about halfway then goes black. Any ideas? (I'll try & upload my log real quick)

**Comment by EggyBoi** [comment]
Also, what SMBIOS did you use for yours?

**Comment by EggyBoi** [comment]
[opencore-2022-06-09-165816.txt](https://github.com/QuanTrieuPCYT/Dell-Latitude-5480_Hackintosh/files/8874306/opencore-2022-06-09-165816.txt)

**Comment by EggyBoi** [comment]
Well, I managed to fix it. No clue how, sorry for wasting your time haha.
